on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run Common Lisp tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install libyaml-dev
      run: sudo apt-get install libyaml-dev
    - name: Run tests (Common Lisp Rove)
      uses: alangalvino/github-actions-cl-rove@main
