on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp: [sbcl-bin]
    name: A job to test Common Lisp project
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install libyaml-dev
      run: sudo apt-get install libyaml-dev
    - name: Install roswell dependencies
      run: sudo apt-get -y install curl libcurl3-gnutls make
    - name: Download and install roswell
      run: curl -L https://github.com/roswell/roswell/releases/download/v19.08.10.101/roswell_19.08.10.101-1_amd64.deb --output roswell.deb && sudo dpkg -i roswell.deb
    - name: Setup roswell
      run: ros install sbcl-bin && ros install rove
    - name: Run Common Lisp tests (Rove)
      run: sudo ./tests/run-tests.sh
